
APP_MODULES := cannonball sdl-1.2

APP_AVAILABLE_STATIC_LIBS :=
APP_ABI := armeabi

SDL_JAVA_PACKAGE_PATH := com_octodev_cannonball

SDL_CURDIR_PATH := com.octodev.cannonball

SDL_TRACKBALL_KEYUP_DELAY := 1

SDL_VIDEO_RENDER_RESIZE := 1

COMPILED_LIBRARIES := 

APPLICATION_ADDITIONAL_CFLAGS := -finline-functions -O2 -DBUILD_TYPE=LINUX32 -DTARGET_LNX=1 -Werror=strict-aliasing -Werror=cast-align -Werror=pointer-arith -Werror=address
APPLICATION_ADDITIONAL_LDFLAGS := 
APPLICATION_OVERLAPS_SYSTEM_HEADERS := n
APPLICATION_SUBDIRS_BUILD := src/*
APPLICATION_BUILD_EXCLUDE := 
APPLICATION_CUSTOM_BUILD_SCRIPT := 

SDL_ADDITIONAL_CFLAGS := -DSDL_ANDROID_KEYCODE_MOUSE=UNKNOWN -DSDL_ANDROID_KEYCODE_0=LCTRL -DSDL_ANDROID_KEYCODE_1=LALT -DSDL_ANDROID_KEYCODE_2=SPACE -DSDL_ANDROID_KEYCODE_3=RETURN -DSDL_ANDROID_KEYCODE_4=RETURN
SDL_VERSION := 1.2

