// This file is AUTO GENERATED by CMake.
#pragma once
#include "SDL_video.h"
const static char* FILENAME_CONFIG = "./config.xml";
const static char* FILENAME_SCORES = "./hiscores";
const static char* FILENAME_TTRIAL = "./hiscores_timetrial";
const static char* FILENAME_CONT   = "./hiscores_continuous";
const static int SDL_FLAGS = SDL_SWSURFACE | SDL_DOUBLEBUF;
#ifdef __ANDROID__
const static int SDL_BPP = 16;
#else
const static int SDL_BPP = 32;
#endif